version: 2
jobs:
  build:
    docker:
      - image: projectida/nrts-builder:0.2
    steps:
      - run:
          name: Create dirs
          command: mkdir src_root && mkdir bin && mkdir lib
      - run:
          name: Go to src_root
          command: cd src_root
      - run:
          name: Checkout NRTS src repo
          command: git clone https://danauerbach:$GITHUB_AUTH@github.com/ProjectIDA/src.git src
      - run:
          name: Enter src repo
          command: cd src
      # - run:
      #     name: Checkout lib330 repo
      #     command: git clone https://danauerbach:$GITHUB_AUTH@github.com/ProjectIDA/lib330.git lib330
      - run:
          name: open tcsh
          command: /bin/tcsh
      - run:
          name: Setup NRTS build env
          command: |
            source env/platform
            source env/envrc
            source env/pathrc
            source env/aliases
      - run:
          name: Make NRTS
          command: cd src && make
