version: 2
jobs:
  build:
    docker:
      - image: projectida/nrts-builder:0.2
    steps:
      - run:
          name: Create dirs
          command: mkdir src_root && mkdir bin && mkdir lib
      - run:
          name: Go to src_root
          command: cd src_root
      - run:
          name: Checkout repo
          command: git clone https://danauerbach:$GITHUB_AUTH@github.com/ProjectIDA/src.git src
      - run:
          name: Make NRTS
          command: cd src && make
