#!/bin/csh -f
#
# start/stop/restart SeedLink server
#
# $Id: ringserver,v 1.1 2013/01/17 17:38:36 dechavez Exp $

set setup = ~nrts/scripts/ScriptSetup
if (! -e $setup) then
    echo "Missing $setup"
    exit 1
endif
source $setup

set mypid = $$

set restart = 0
set chatty = 1

set masterlist = `pgrep -x ringserver`
set pidlist = ""
foreach pid ($masterlist)
    if ($pid != $$) set pidlist = "$pid $pidlist"
end
if ("$pidlist" == "") shift pidlist

if ($#argv == 1) then
    switch ($argv[1])
      case start:
        goto start
        breaksw

      case stop
        goto stop
        breaksw

      case restart
        set restart = 1
        goto stop
        breaksw

      case bounce
        set restart = 1
        set chatty = 0
        goto stop
        breaksw
    endsw
endif

echo "Usage: $NRTS_HOME/etc/init.d/ringserver { start | stop | restart | bounce }"
exit 1

# Start server

start:

if ($#pidlist != 0) then
    if ($chatty) echo "SeedLink server is already running (pid $pidlist)"
else
    StartSeedLink
endif
exit 0

# Stop server

stop:

if ($#pidlist == 0) then
    if ($chatty) echo "SeedLink server is not running"
else
    foreach pid ($pidlist)
        if ($chatty) echo "Stopping ringserver process $pid"
        kill -TERM $pid
        @ count = 0;
        while ($pid != 0)
            if ($count > 10) then
                if ($chatty) echo "ringserver (pid $pid) won't die, forced"
                kill -9 $pid
            endif
            sleep 1
            nohup kill -0 $pid >& /dev/null
            if ($status == 1) set pid = 0
        end
    end
    while ($#pidlist != 0) 
        shift pidlist
    end
endif

if ($restart) goto start
exit 0

# Revision History
#
# $Log: ringserver,v $
# Revision 1.1  2013/01/17 17:38:36  dechavez
# created
#
