# $Id: Makefile,v 1.53 2017/09/28 20:42:16 dauerbach Exp $
# Make all libraries

all: \
    addoss \
    cssio \
    dali \
    dbio \
    detect \
    dmc \
    dpm \
    e300 \
    filter \
    iacp \
    iboot \
    ida \
    ida10 \
    isi \
    isidb \
    isidl \
    liss \
    logio \
    md5 \
    mio \
    modbus \
    mseed \
    msgq \
    myxml \
    nrts \
    oldttyio \
    paro \
    q330 \
    qdp \
    qdplus \
    qdpxml \
    qio \
    sacio \
    sbd \
    sclk \
    seed \
    ttyio \
    udpio \
    util \
    wg \
    xfer
    #tristar \

idadcc: \
    dccdb

addoss: FORCE
	cd addoss; $(MAKE)

cssio: FORCE
	cd cssio; $(MAKE)

dali: FORCE
	cd dali; $(MAKE)

dbio: FORCE
	cd dbio; $(MAKE)

dccdb: FORCE
	cd dccdb; $(MAKE)

detect: FORCE
	cd detect; $(MAKE)

dmc: FORCE
	cd dmc; $(MAKE)

dpm: FORCE
	cd dpm; $(MAKE)

e300: FORCE
	cd e300; $(MAKE)

filter: FORCE
	cd filter; $(MAKE)

iacp: FORCE
	cd iacp; $(MAKE)

iboot: FORCE
	cd iboot; $(MAKE)

ida: FORCE
	cd ida; $(MAKE)

ida10: FORCE
	cd ida10; $(MAKE)

isi: FORCE
	cd isi; $(MAKE)

isidb: FORCE
	cd isidb; $(MAKE)

isidl: FORCE
	cd isidl; $(MAKE)

iso9660: FORCE
	cd iso9660; $(MAKE)

isp: FORCE
	cd isp; $(MAKE)

liss: FORCE
	cd liss; $(MAKE)

logio: FORCE
	cd logio; $(MAKE)

md5: FORCE
	cd md5; $(MAKE)

mio: FORCE
	cd mio; $(MAKE)

modbus: FORCE
	cd modbus; $(MAKE)

mseed: FORCE
	cd mseed; $(MAKE)

msgq: FORCE
	cd msgq; $(MAKE)

myxml: FORCE
	cd myxml; $(MAKE)

mtio: FORCE
	cd mtio; $(MAKE)

nrts: FORCE
	cd nrts; $(MAKE)

oldmsgq: FORCE
	cd oldmsgq; $(MAKE)

oldmtio: FORCE
	cd oldmtio; $(MAKE)

oldparo: FORCE
	cd oldparo; $(MAKE)

oldttyio: FORCE
	cd oldttyio; $(MAKE)

paro: FORCE
	cd paro; $(MAKE)

q330: FORCE
	cd q330; $(MAKE)

qdp: FORCE
	cd qdp; $(MAKE)

qdplus: FORCE
	cd qdplus; $(MAKE)

qdpxml: FORCE
	cd qdpxml; $(MAKE)

qio: FORCE
	cd qio; $(MAKE)

sacio: FORCE
	cd sacio; $(MAKE)

sanio: FORCE
	cd sanio; $(MAKE)

sbd: FORCE
	cd sbd; $(MAKE)

sclk: FORCE
	cd sclk; $(MAKE)

seed: FORCE
	cd seed; $(MAKE)

tristar: FORCE
	cd tristar; $(MAKE)

ttyio: FORCE
	cd ttyio; $(MAKE)

udpio: FORCE
	cd udpio; $(MAKE)

util: FORCE
	cd util; $(MAKE)

wg: FORCE
	cd wg; $(MAKE)

xfer: FORCE
	cd xfer; $(MAKE)

clean: FORCE
	cd addoss;   $(MAKE) $@
	cd cssio;    $(MAKE) $@
	cd dali;     $(MAKE) $@
	cd dbio;     $(MAKE) $@
	cd dccdb;    $(MAKE) $@
	cd detect;   $(MAKE) $@
	cd dmc;      $(MAKE) $@
	cd dpm;      $(MAKE) $@
	cd e300;     $(MAKE) $@
	cd filter;   $(MAKE) $@
	cd iacp;     $(MAKE) $@
	cd iboot;    $(MAKE) $@
	cd ida;      $(MAKE) $@
	cd ida10;    $(MAKE) $@
	cd isi;      $(MAKE) $@
	cd isidb;    $(MAKE) $@
	cd isidl;    $(MAKE) $@
	cd iso9660;  $(MAKE) $@
	cd isp;      $(MAKE) $@
	cd liss;     $(MAKE) $@
	cd logio;    $(MAKE) $@
	cd md5;      $(MAKE) $@
	cd mio;      $(MAKE) $@
	cd modbus;   $(MAKE) $@
	cd mseed;    $(MAKE) $@
	cd msgq;     $(MAKE) $@
	cd myxml;    $(MAKE) $@
	cd mtio;     $(MAKE) $@
	cd nrts;     $(MAKE) $@
	cd oldmsgq;  $(MAKE) $@
	cd oldmtio;  $(MAKE) $@
	cd oldparo;  $(MAKE) $@
	cd oldttyio; $(MAKE) $@
	cd paro;     $(MAKE) $@
	cd q330;     $(MAKE) $@
	cd qdp;      $(MAKE) $@
	cd qdplus;   $(MAKE) $@
	cd qdpxml;   $(MAKE) $@
	cd qio;      $(MAKE) $@
	cd sacio;    $(MAKE) $@
	cd sanio;    $(MAKE) $@
	cd sbd;      $(MAKE) $@
	cd sclk;     $(MAKE) $@
	cd seed;     $(MAKE) $@
	cd tristar;  $(MAKE) $@
	cd ttyio;    $(MAKE) $@
	cd udpio;    $(MAKE) $@
	cd util;     $(MAKE) $@
	cd wg;       $(MAKE) $@
	cd xfer;     $(MAKE) $@

remove: FORCE
	cd addoss;   $(MAKE) $@
	cd cssio;    $(MAKE) $@
	cd dali;     $(MAKE) $@
	cd dbio;     $(MAKE) $@
	cd dccdb;    $(MAKE) $@
	cd detect;   $(MAKE) $@
	cd dmc;      $(MAKE) $@
	cd dpm;      $(MAKE) $@
	cd e300;     $(MAKE) $@
	cd filter;   $(MAKE) $@
	cd iacp;     $(MAKE) $@
	cd iboot;    $(MAKE) $@
	cd ida;      $(MAKE) $@
	cd ida10;    $(MAKE) $@
	cd isi;      $(MAKE) $@
	cd isidb;    $(MAKE) $@
	cd isidl;    $(MAKE) $@
	cd iso9660;  $(MAKE) $@
	cd isp;      $(MAKE) $@
	cd liss;     $(MAKE) $@
	cd logio;    $(MAKE) $@
	cd md5;      $(MAKE) $@
	cd mio;      $(MAKE) $@
	cd modbus;   $(MAKE) $@
	cd mseed;    $(MAKE) $@
	cd msgq;     $(MAKE) $@
	cd myxml;    $(MAKE) $@
	cd mtio;     $(MAKE) $@
	cd nrts;     $(MAKE) $@
	cd oldmsgq;  $(MAKE) $@
	cd oldmtio;  $(MAKE) $@
	cd oldparo;  $(MAKE) $@
	cd oldttyio; $(MAKE) $@
	cd paro;     $(MAKE) $@
	cd q330;     $(MAKE) $@
	cd qdp;      $(MAKE) $@
	cd qdplus;   $(MAKE) $@
	cd qdpxml;   $(MAKE) $@
	cd qio;      $(MAKE) $@
	cd sacio;    $(MAKE) $@
	cd sanio;    $(MAKE) $@
	cd sbd;      $(MAKE) $@
	cd sclk;     $(MAKE) $@
	cd seed;     $(MAKE) $@
	cd tristar;  $(MAKE) $@
	cd ttyio;    $(MAKE) $@
	cd udpio;    $(MAKE) $@
	cd util;     $(MAKE) $@
	cd wg;       $(MAKE) $@
	cd xfer;     $(MAKE) $@
	rm -rf ../../lib/$(PLATFORM)

REMOVE: FORCE
	cd addoss;   $(MAKE) $@
	cd cssio;    $(MAKE) $@
	cd dali;     $(MAKE) $@
	cd dbio;     $(MAKE) $@
	cd dccdb;    $(MAKE) $@
	cd detect;   $(MAKE) $@
	cd dmc;      $(MAKE) $@
	cd dpm;      $(MAKE) $@
	cd e300;     $(MAKE) $@
	cd filter;   $(MAKE) $@
	cd iacp;     $(MAKE) $@
	cd iboot;    $(MAKE) $@
	cd ida;      $(MAKE) $@
	cd ida10;    $(MAKE) $@
	cd isi;      $(MAKE) $@
	cd isidb;    $(MAKE) $@
	cd isidl;    $(MAKE) $@
	cd iso9660;  $(MAKE) $@
	cd isp;      $(MAKE) $@
	cd liss;     $(MAKE) $@
	cd logio;    $(MAKE) $@
	cd md5;      $(MAKE) $@
	cd mio;      $(MAKE) $@
	cd modbus;   $(MAKE) $@
	cd mseed;    $(MAKE) $@
	cd msgq;     $(MAKE) $@
	cd myxml;    $(MAKE) $@
	cd mtio;     $(MAKE) $@
	cd nrts;     $(MAKE) $@
	cd oldmsgq;  $(MAKE) $@
	cd oldmtio;  $(MAKE) $@
	cd oldparo;  $(MAKE) $@
	cd oldttyio; $(MAKE) $@
	cd paro;     $(MAKE) $@
	cd q330;     $(MAKE) $@
	cd qdp;      $(MAKE) $@
	cd qdplus;   $(MAKE) $@
	cd qdpxml;   $(MAKE) $@
	cd qio;      $(MAKE) $@
	cd sacio;    $(MAKE) $@
	cd sanio;    $(MAKE) $@
	cd sbd;      $(MAKE) $@
	cd sclk;     $(MAKE) $@
	cd seed;     $(MAKE) $@
	cd tristar;  $(MAKE) $@
	cd ttyio;    $(MAKE) $@
	cd udpio;    $(MAKE) $@
	cd util;     $(MAKE) $@
	cd wg;       $(MAKE) $@
	cd xfer;     $(MAKE) $@
	rm -rf ../../lib/$(PLATFORM)

FORCE:
