# $Id: Makefile,v 1.55 2017/12/21 21:26:41 dauerbach Exp $
# Make all libraries

all: \
    cssio \
    dali \
    dbio \
    detect \
    dmc \
    e300 \
    filter \
    iacp \
    iboot \
    ida \
    ida10 \
    isi \
    isidb \
    isidl \
    liss \
    logio \
    md5 \
    modbus \
    mseed \
    msgq \
    myxml \
    nrts \
    paro \
    q330 \
    qdp \
    qdplus \
    qdpxml \
    qio \
    sacio \
    sbd \
    seed \
    ttyio \
    udpio \
    util \
    xfer
    #tristar \

idadcc: \
    cssio \
    dbio \
    dccdb \
    dmc \
    filter \
    iacp \
    ida \
    ida10 \
    isi \
    isidb \
    liss \
    logio \
    mseed \
    util

cssio: FORCE
	cd cssio; $(MAKE)

dali: FORCE
	cd dali; $(MAKE)

dbio: FORCE
	cd dbio; $(MAKE)

dccdb: FORCE
	cd dccdb; $(MAKE)

detect: FORCE
	cd detect; $(MAKE)

dmc: FORCE
	cd dmc; $(MAKE)


e300: FORCE
	cd e300; $(MAKE)

filter: FORCE
	cd filter; $(MAKE)

iacp: FORCE
	cd iacp; $(MAKE)

iboot: FORCE
	cd iboot; $(MAKE)

ida: FORCE
	cd ida; $(MAKE)

ida10: FORCE
	cd ida10; $(MAKE)

isi: FORCE
	cd isi; $(MAKE)

isidb: FORCE
	cd isidb; $(MAKE)

isidl: FORCE
	cd isidl; $(MAKE)



liss: FORCE
	cd liss; $(MAKE)

logio: FORCE
	cd logio; $(MAKE)

md5: FORCE
	cd md5; $(MAKE)


modbus: FORCE
	cd modbus; $(MAKE)

mseed: FORCE
	cd mseed; $(MAKE)

msgq: FORCE
	cd msgq; $(MAKE)

myxml: FORCE
	cd myxml; $(MAKE)


nrts: FORCE
	cd nrts; $(MAKE)





paro: FORCE
	cd paro; $(MAKE)

q330: FORCE
	cd q330; $(MAKE)

qdp: FORCE
	cd qdp; $(MAKE)

qdplus: FORCE
	cd qdplus; $(MAKE)

qdpxml: FORCE
	cd qdpxml; $(MAKE)

qio: FORCE
	cd qio; $(MAKE)

sacio: FORCE
	cd sacio; $(MAKE)


sbd: FORCE
	cd sbd; $(MAKE)


seed: FORCE
	cd seed; $(MAKE)

tristar: FORCE
	cd tristar; $(MAKE)

ttyio: FORCE
	cd ttyio; $(MAKE)

udpio: FORCE
	cd udpio; $(MAKE)

util: FORCE
	cd util; $(MAKE)

xfer: FORCE
	cd xfer; $(MAKE)

clean: FORCE
	cd cssio;    $(MAKE) $@
	cd dali;     $(MAKE) $@
	cd dbio;     $(MAKE) $@
	cd dccdb;    $(MAKE) $@
	cd detect;   $(MAKE) $@
	cd dmc;      $(MAKE) $@
	cd e300;     $(MAKE) $@
	cd filter;   $(MAKE) $@
	cd iacp;     $(MAKE) $@
	cd iboot;    $(MAKE) $@
	cd ida;      $(MAKE) $@
	cd ida10;    $(MAKE) $@
	cd isi;      $(MAKE) $@
	cd isidb;    $(MAKE) $@
	cd isidl;    $(MAKE) $@
	cd liss;     $(MAKE) $@
	cd logio;    $(MAKE) $@
	cd md5;      $(MAKE) $@
	cd modbus;   $(MAKE) $@
	cd mseed;    $(MAKE) $@
	cd msgq;     $(MAKE) $@
	cd myxml;    $(MAKE) $@
	cd nrts;     $(MAKE) $@
	cd paro;     $(MAKE) $@
	cd q330;     $(MAKE) $@
	cd qdp;      $(MAKE) $@
	cd qdplus;   $(MAKE) $@
	cd qdpxml;   $(MAKE) $@
	cd qio;      $(MAKE) $@
	cd sacio;    $(MAKE) $@
	cd sbd;      $(MAKE) $@
	cd seed;     $(MAKE) $@
	cd tristar;  $(MAKE) $@
	cd ttyio;    $(MAKE) $@
	cd udpio;    $(MAKE) $@
	cd util;     $(MAKE) $@
	cd xfer;     $(MAKE) $@

remove: FORCE
	cd cssio;    $(MAKE) $@
	cd dali;     $(MAKE) $@
	cd dbio;     $(MAKE) $@
	cd dccdb;    $(MAKE) $@
	cd detect;   $(MAKE) $@
	cd dmc;      $(MAKE) $@
	cd e300;     $(MAKE) $@
	cd filter;   $(MAKE) $@
	cd iacp;     $(MAKE) $@
	cd iboot;    $(MAKE) $@
	cd ida;      $(MAKE) $@
	cd ida10;    $(MAKE) $@
	cd isi;      $(MAKE) $@
	cd isidb;    $(MAKE) $@
	cd isidl;    $(MAKE) $@
	cd liss;     $(MAKE) $@
	cd logio;    $(MAKE) $@
	cd md5;      $(MAKE) $@
	cd modbus;   $(MAKE) $@
	cd mseed;    $(MAKE) $@
	cd msgq;     $(MAKE) $@
	cd myxml;    $(MAKE) $@
	cd nrts;     $(MAKE) $@
	cd paro;     $(MAKE) $@
	cd q330;     $(MAKE) $@
	cd qdp;      $(MAKE) $@
	cd qdplus;   $(MAKE) $@
	cd qdpxml;   $(MAKE) $@
	cd qio;      $(MAKE) $@
	cd sacio;    $(MAKE) $@
	cd sbd;      $(MAKE) $@
	cd seed;     $(MAKE) $@
	cd tristar;  $(MAKE) $@
	cd ttyio;    $(MAKE) $@
	cd udpio;    $(MAKE) $@
	cd util;     $(MAKE) $@
	cd xfer;     $(MAKE) $@
	rm -rf ../../lib/$(PLATFORM)

REMOVE: FORCE
	cd cssio;    $(MAKE) $@
	cd dali;     $(MAKE) $@
	cd dbio;     $(MAKE) $@
	cd dccdb;    $(MAKE) $@
	cd detect;   $(MAKE) $@
	cd dmc;      $(MAKE) $@
	cd e300;     $(MAKE) $@
	cd filter;   $(MAKE) $@
	cd iacp;     $(MAKE) $@
	cd iboot;    $(MAKE) $@
	cd ida;      $(MAKE) $@
	cd ida10;    $(MAKE) $@
	cd isi;      $(MAKE) $@
	cd isidb;    $(MAKE) $@
	cd isidl;    $(MAKE) $@
	cd liss;     $(MAKE) $@
	cd logio;    $(MAKE) $@
	cd md5;      $(MAKE) $@
	cd modbus;   $(MAKE) $@
	cd mseed;    $(MAKE) $@
	cd msgq;     $(MAKE) $@
	cd myxml;    $(MAKE) $@
	cd nrts;     $(MAKE) $@
	cd paro;     $(MAKE) $@
	cd q330;     $(MAKE) $@
	cd qdp;      $(MAKE) $@
	cd qdplus;   $(MAKE) $@
	cd qdpxml;   $(MAKE) $@
	cd qio;      $(MAKE) $@
	cd sacio;    $(MAKE) $@
	cd sbd;      $(MAKE) $@
	cd seed;     $(MAKE) $@
	cd tristar;  $(MAKE) $@
	cd ttyio;    $(MAKE) $@
	cd udpio;    $(MAKE) $@
	cd util;     $(MAKE) $@
	cd xfer;     $(MAKE) $@
	rm -rf ../../lib/$(PLATFORM)

FORCE:
