#!/bin/sh
#
# start/stop NRTS processes
#
# $Id: nrts,v 1.1 2015/12/18 18:56:59 dechavez Exp $

. /etc/rc.subr

name="nrts"
rcvar="${name}_enable"
start_cmd="${name}_start"
stop_cmd="${name}_stop"

nrts_start()
{
    NRTSRC="/usr/nrts/etc/start/boot"
    if [ -f ${NRTSRC} ]; then
        echo "Starting NRTS"
        csh ${NRTSRC} > /dev/null &
    fi
}
        
nrts_stop()
{
    echo "Stopping NRTS"
    pkill -TERM -x isid
    pkill -TERM -x isidl
    pkill -TERM -x ispd
    pkill -TERM -x nrts_edes
    pkill -TERM -x qhlp
    pkill -TERM -x tristar10
    pkill -TERM -x paro10
    sleep 2
    pkill -TERM -x ringserver
}

load_rc_config ${name}
run_rc_command "$@"

# $Log: nrts,v $
# Revision 1.1  2015/12/18 18:56:59  dechavez
# created for FreeBSD 10.1
#
