#!/bin/csh -f
#
# Kill any ssh tunnels
       
set list = `/bin/ps -ax -o user,pid,command | grep -E "ssh +tunnel@idahub" | grep -v grep | awk '{print$2}'`
foreach pid ($list)
    kill -TERM $pid  >& /dev/null
end
       
exit 0
       
# Revision History - SEE GIT LOG for current revision history.
#
# Revision 1.3  2015/05/13 17:48:00  dechavez
# fix the Nov(ember) list all processes bug
#
# Revision 1.2  2012/10/05 19:18:04  dechavez
# improved? rule to capture the tunnel instance (grep on N arg)
#
# Revision 1.1  2012/10/05 19:05:22  dechavez
# created
#
