#!/bin/csh -f
# $Id: isiCreateDiskLoops,v 1.6 2015/12/10 00:00:15 dechavez Exp $
#
# Create all ISI and NRTS disk loops

set myname = isiCreateDiskLoops

# General setup

set setup  = ~nrts/scripts/ScriptSetup
if (! -e $setup ) then
    echo "missing $setup"
    goto failure
endif
source $setup

# Command line setup

set error = 0
if ($#argv == 0) then
    set SiteList = "$SystemsList"
else 
    set SiteList = "$argv"
endif

# Loop for each site

foreach site ($SiteList)

    set SiteDir    = $NRTS_HOME/$site

    if (-e $SiteDir/cnf) then
        nrts_mkdl $site
        isimkdl type=ida $site
    else
        isimkdl type=qdp $site
    endif

    mkdir $SiteDir/tee >& /dev/null
    mkdir $SiteDir/iso/done $SiteDir/iso/done/images $SiteDir/iso/done/gziped >& /dev/null
end

success:
exit 0

failure:
exit 1

# Revision History
#
# $Log: isiCreateDiskLoops,v $
# Revision 1.6  2015/12/10 00:00:15  dechavez
# undid the previous change, now use ~nrts instead of NRTS_HOME to load the setup script
# (didn't work in cron, duh)
#
# Revision 1.5  2015/12/08 16:51:14  dechavez
# fixed cvs log comment for previous commit (sigh, it's going to be a long day)
#
# Revision 1.4  2015/12/08 16:17:16  dechavez
# fixed typo in creating iso subdirs (note to self: test before committing!)
#
# Revision 1.3  2015/12/07 21:24:29  dechavez
# don't assume user nrts (use NRTS_HOME environment varible instead)
#
# Revision 1.2  2015/12/07 20:34:04  dechavez
# Create iso subdirs
#
# Revision 1.1  2008/12/16 18:26:19  dechavez
# initial release
