#!/bin/tcsh -f
# $Id: isils,v 1.3 2015/10/28 16:15:08 dechavez Exp $
# List start/end times for each .gz file in the current directory

if ($#argv == 1) then
    set rev = $argv
else if (-e ./contents.txt) then
    set rev = `cat contents.txt | awk '{print $2}'`
else
    echo "need to specify rev code"
    exit 1
endif

foreach gz (*.gz)
    echo -n $gz
    echo -n ": "
    gunzip -c $gz | idaspan rev=$rev
end

# Revision History
#
# $Log: isils,v $
# Revision 1.3  2015/10/28 16:15:08  dechavez
# replaced gzcat with gunzip -c
#
# Revision 1.2  2009/06/24 21:11:09  dechavez
# changed to tcsh to permit longer *.gz argument strings
#
# Revision 1.1  2005/11/04 01:08:36  dechavez
# initial release
#
