#!/bin/csh -f
# $Id: isiPurgeOldImages,v 1.6 2015/12/10 00:00:16 dechavez Exp $
#
# Move old, unburned ISO images to done area

set debug  = 0
set myname = isiPurgeOldImages
set dummy  = ________.iso

if ($debug) logger -t $myname"[$$]" -p local0.info "begin"

# General setup

set setup  = ~nrts/scripts/ScriptSetup
if (! -e $setup ) then
    set message = "missing $setup"
    logger -t $myname"[$$]" -p local0.info "$message"
    echo "${myname}: $message"
    goto failure
endif
source $setup
if ($debug) logger -t $myname"[$$]" -p local0.info "$setup OK"

# Command line setup

if ($#argv != 2) then
        echo "usage: $myname IsoDir DoneIsoDir"
        goto failure
endif

set IsoDir     = $argv[1]
set DoneIsoDir = $argv[2]

# Work in the ISO directory

cd $IsoDir
if ($status != 0) then
    echo "ERROR: can't chdir $IsoDir"
    goto failure
endif

# Count the ISO images.  Convoluted stuff at the front is to allow for
# the case where there are zero unburned images waiting.

touch $dummy
set list = ????????.iso
@ numiso = `echo $list | wc -w`
rm -f $dummy
if ($numiso == 1) goto success

# At this point we know we have at least one real ISO image

set list = ????????.iso
@ numiso = `echo $list | wc -w`

while ($numiso > $MaxUnburnedISOImages)
    if ($list[1] != $dummy) then
        set command = "mv $list[1] $DoneIsoDir"
        if ($debug) logger -t $myname"[$$]" -p local0.info "$command"
        $command
        shift list
        @ numiso--
    endif
end

# Normal exit

success:
if ($debug) logger -t $myname"[$$]" -p local0.info "completed OK"
exit 0

failure:
logger -t $myname"[$$]" -p local0.info "exit 1"
exit 1

