#!/bin/csh -f
#
# Update disk loop from remote and break connection when
# current.  This is meant for bringing in data from places
# where a continuous feed isn't practical or permitted
# (such as NIL)

set debug  = 1
set myname = isiRequestOnce

if ($debug) logger -t $myname"[$$]" -p local0.info "begin"

# General setup

set setup  = ~nrts/scripts/ScriptSetup
if (! -e $setup ) then
    set message = "missing $setup"
    logger -t $myname"[$$]" -p local0.info "$message"
    echo "${myname}: $message"
    goto failure
endif
source $setup
if ($debug) logger -t $myname"[$$]" -p local0.info "$setup OK"

if ($#argv != 4) then
    set message = "bad command line"
    logger -t $myname"[$$]" -p local0.info "$message"
    echo "${myname}: $message"
    echo "usage: $myname server sta"
    goto failure
endif

set server = $argv[1]
set sta    = $argv[2]
set maxdur = $argv[3]
set slsrvr = $argv[4]
set timeout = 60

set command = "isidl isi=${server} $sta end=newest log=syslogd:local0 to=$timeout maxdur=$maxdur seedlink=${slsrvr}:16000:512:500:II -nosync"
if ($debug) logger -t $myname"[$$]" -p local0.info "$command"
$command

if ($debug) logger -t $myname"[$$]" -p local0.info "completed OK"
exit 0

failure:
logger -t $myname"[$$]" -p local0.info "exit 1"
exit 1

# Revision History
#
# $Log: isiRequestOnce,v $
# Revision 1.2  2016/07/28 18:25:16  dechavez
# fixed bug in arg count check
#
# Revision 1.1  2016/07/28 18:22:06  dechavez
# committed
#
