#!/bin/csh -f
# $Id: nrtsSetPerms,v 1.7 2013/01/14 23:55:32 dechavez Exp $

set setuidfiles = ""
set setuidfiles = "$setuidfiles nrts_edes"

if ($#argv != 1) then
    echo "usage: nrtsSetPerms NRTS_bin_dir"
    exit 1
endif

set bindir = $argv[1]
if (! -d $bindir) then
    echo "missing $bindir"
    exit 1
endif

cd $bindir
if ($status != 0) then
    echo "can't cd to $bindir"
    exit 1
endif

chmod 555 *
foreach file ($setuidfiles)
    if (-e $file) chmod 4555 $file
end
