#!/bin/csh -f

set myname = qGpsLocation

# General setup

set setup  = ~nrts/scripts/ScriptSetup
if (! -e $setup ) then
    echo "missing $setup"
    goto failure
endif
source $setup

# Command line setup

set error = 0
if ($#argv == 0) then
    set SiteList = "$SystemsList"
else
    set SiteList = "$argv"
endif

# Loop for each site

foreach site ($SiteList)

    foreach loc (00 10)

        echo "${site}${loc}:   X" | awk '{print substr($0, 1, 7)}' | tr '\n' ' '
        tssh ${site} q330 ${site}${loc} status | egrep "(Latitude|Longitude)" | tr '\n' ' ' | awk '{print $3, $6}'
        if ($status != 0) then
            echo ""
            echo "   Error communicating with ${site}${loc}"
        else
            # echo ""
        endif


    end
end

