#!/bin/csh -f

set myname = qGpsLocation

# General setup

set setup  = ~nrts/scripts/ScriptSetup
if (! -e $setup ) then
    echo "missing $setup"
    goto failure
endif
source $setup

# Command line setup

set error = 0
if ($#argv == 0) then
    set SiteList = "$SystemsList"
else
    set SiteList = "$argv"
endif

# Loop for each site

foreach site ($SiteList)

    foreach loc (00 10)

        echo GPS Lat/Lon from: ${site}${loc}:
        tssh ${site} q330 ${site}${loc} status | egrep "(Latitude|Longitude)"
        if ($status != 0) then
            echo Error communicating with ${site}${loc}
        endif

    end
end

