#!/bin/csh -f
#
# SeedLink startup script
#

foreach rcfile ($NRTS_HOME/.platform $NRTS_HOME/.envrc)
    if (-e $rcfile) then
        source $rcfile
    else
        echo "warning: missing $rcfile"
    endif
endif

if ($#argv > 0) then
    set SeedLink = $argv[1]
else
    set SeedLink = $NRTS_HOME/SeedLink
endif

set bindir = /usr/local/bin
set server = $bindir/ringserver
set conf   = $SeedLink/ring.conf

foreach entity ($server $conf)
    if (! -e $entity) then
        echo "SeedLink support disabled: missing $entity"
        exit 1
    endif
end

set path = ($bindir $path)
#chmod 4555 $server

(ringserver $conf >& /dev/null) &

