#!/bin/csh -f

if ($#argv != 2) then
	echo "usage: UpdateNrtsLatencyPage Server HtmlFileName"
	exit 1
endif

set path = (/usr/nrts/bin /ida/nrts/bin $path)

set isiserver = $argv[1]
set webserver =  $argv[2]

set webpath = "Telemetry"
set webpathTEST = "TelemetryTest"
set htdocpath = "/ida/web"
set stationdir = "Stations"

set command = "isiwww isiserver=$isiserver webserver=$webserver webpath=$webpath stationdir=$stationdir htdocpath=$htdocpath"
$command

# for testing into 'TelemetryTest" directory. idahub only
if ($isiserver == idahub.ucsd.edu) then
    set command = "isiwww2 isiserver=$isiserver webserver=$webserver webpath=$webpathTEST stationdir=$stationdir htdocpath=$htdocpath"
    $command
endif
