#!/bin/csh -f
#
# Kill any ssh tunnels

set myname = BounceTunnels
set debug = 1

set list = `/bin/ps -ax -o pid,user,command | egrep "nrts +ssh -f -N" | awk '{print $1}'`
foreach pid ($list)

    if ($debug) then
        set cmd = `ps -p $pid -o command | grep -v COMMAND`
        logger -t $myname"[$$]" -p local0.debug "Bouncing tunnel:$pid $cmd"
    endif

    kill -TERM $pid  >& /dev/null

    if ($debug) logger -t $myname"[$$]" -p local0.debug "Bounced: $pid"

end

exit 0

# Revision History - SEE GIT LOG for current revision history.
#
# $Log: BounceTunnels,v $
# Revision 1.3  2015/05/13 17:48:00  dechavez
# fix the Nov(ember) list all processes bug
#
# Revision 1.2  2012/10/05 19:18:04  dechavez
# improved? rule to capture the tunnel instance (grep on N arg)
#
# Revision 1.1  2012/10/05 19:05:22  dechavez
# created
#
